FROM php:7.2-fpm
RUN apt-get update && apt-get install -y \
        cron \
        unzip \
    && docker-php-ext-install pdo_mysql
#RUN apt-get update && apt-get install pdo pdo_mysql
CMD ["php-fpm"]  
EXPOSE 9000
